### ISSUE TITLE
PHP warning due to typo: `reutrn` instead of `return`

### ISSUE THREAD

**Issue by jhogervorst** [coffee2code/add-admin-javascript#1]
The following line contains a typo:

https://github.com/coffee2code/add-admin-javascript/blob/e919476c406807ddc3e1b6cdc257520ae21ae7e5/add-admin-javascript.php#L185

This causes the following warning:

> PHP Warning: Use of undefined constant reutrn - assumed 'reutrn' (this will throw an Error in a future version of PHP) in wp-content/plugins/add-admin-javascript/add-admin-javascript.php on line 185

**Comment by coffee2code** [comment]
Thanks for reporting the bug and the PR! v1.8.1 has been released with the fix merged.
